name: video_dewatermark
description: 视频去水印工具
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_new: ^0.2.0
  video_player: ^2.8.0
  image_picker: ^1.0.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  image: ^4.1.0
  gal: ^2.3.0  # 兼容 Android 10+ 分区存储的相册保存插件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
